
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Project113_G3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class RequestGameData
{

    public int Id { get; set; }

    public string RQGUsername { get; set; }

    public string RQGGame { get; set; }

    public string RQGDes { get; set; }

}

}
